// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApi.Data;

#nullable disable

namespace MoviesApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520223748_AddComingMovies")]
    partial class AddComingMovies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MoviesApi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShowing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Premiere")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Actors = "Jack Reynor, Laia Costa, Hayat Kamille",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Description = "En familj stöter på en uråldrig mumie i denna nya tolkning av det klassiska monstret.",
                            Director = "Lee Cronin",
                            DurationMinutes = 134,
                            Genre = "Skräck",
                            ImageUrl = "/images/mummy.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Lee Cronin's The Mummy",
                            Premiere = new DateOnly(2026, 4, 17),
                            Price = 169.0,
                            Title = "The Mummy"
                        },
                        new
                        {
                            Id = 4,
                            Actors = "Michael Johnston, Inde Navarrette, Andy Richter, Cooper Tomlinson, Megan Lawless, Haley Fitzgerald, Darin Toonder, Chloe Breen, Anthony Pavone",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Description = "Efter att ha använt en mystisk \"One Wish Willow\" i hopp om att vinna sin förälskelses hjärta, får en hopplös romantiker precis det han önskar sig. Men han upptäcker snart att för en del önskningar får man betala ett mörkt och fruktansvärt pris.",
                            Director = "Curry Barker",
                            DurationMinutes = 108,
                            Genre = "Skräck",
                            ImageUrl = "/images/obsession.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Obsession",
                            Premiere = new DateOnly(2026, 5, 15),
                            Price = 189.0,
                            Title = "Obsession"
                        },
                        new
                        {
                            Id = 1,
                            Actors = "Hugh Jackman, Emma Thompson, Bella Ramsey",
                            AgeRating = "Från 7 år: Får ses på bio av barn under 7 år i vuxens sällskap.",
                            Description = "I detta roliga och underhållande mysterium, som inte liknar något du sett tidigare, är George en herde som varje kväll läser deckarromaner för sina älskade får, i tron att de omöjligt kan förstå. Men när en mystisk händelse stör livet på gården inser fåren att de själva måste bli detektiver. När de följer ledtrådarna och undersöker mänskliga misstänkta bevisar de att även får kan vara briljanta brottslösare.",
                            Director = "Kyle Balda",
                            DurationMinutes = 109,
                            Genre = "Komedi, Familj, Mysterium",
                            ImageUrl = "/images/fardetektiverna.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "The Sheep Detectives",
                            Premiere = new DateOnly(2026, 5, 8),
                            Price = 119.0,
                            Title = "Fårdetektiverna"
                        },
                        new
                        {
                            Id = 3,
                            Actors = "Karl Urban, Hiroyuki Sanada, Martyn Ford, Lewis Tan, Damon Herriman, Tati Gabrielle, Adeline Rudolph, Tadanobu Asano, Josh Lawson, Jessica McNamee, Mehcad Brooks, Ludi Lin, Joe Taslim, Chin Han, Ana Thu Nguyen, Desmond Chiam, Julian Weeks, Max Huang, CJ. Bloomfield",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Description = "Den här gången ställs fansens favorithjältar – nu tillsammans med Johnny Cage själv – mot varandra i den ultimata, och fullständigt skoningslösa, blodiga kampen för att besegra Shao Kahns mörka härskande som hotar själva existensen av Earthrealm och dess försvarare.",
                            Director = "Simon McQuoid",
                            DurationMinutes = 115,
                            Genre = "Action",
                            ImageUrl = "/images/mortalkombat.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Mortal Kombat II",
                            Premiere = new DateOnly(2026, 5, 8),
                            Price = 159.0,
                            Title = "Mortal Kombat II"
                        },
                        new
                        {
                            Id = 5,
                            Actors = "Ai Mikami, Natsuki Hanae, Hiccorohee, Kana Hanazawa, Mô Chûgakusei",
                            AgeRating = "Från 11 år: Får ses på bio av den som fyllt 7 år i sällskap med vuxen.",
                            Description = "Rita har hamnat i en tidsloop under en utomjordisk invasion, återupplever samma dag om och om igen och blir långsamt en alltmer effektiv krigare. Utmattad av en oändlig rad av dödsögonblick upptäcker hon Keiji, en annan person som hamnat i samma loop.",
                            Director = "Kenichiro Akimoto",
                            DurationMinutes = 86,
                            Genre = "Anime",
                            ImageUrl = "/images/allyouneediskill.jpg",
                            IsShowing = false,
                            OriginalLanguage = "Japanska",
                            OriginalTitle = "All You Need Is Kill",
                            Premiere = new DateOnly(2026, 5, 29),
                            Price = 129.0,
                            Title = "All You Need Is Kill"
                        },
                        new
                        {
                            Id = 6,
                            Actors = "Marlon Wayans, Shawn Wayans, Anna Faris, Regina Hall, Damon Wayans Jr., Gregg Wayans, Kim Wayans, Benny Zielke, Cameron Scott Roberts, Cheri Oteri, Chris Elliott, Dave Sheridan, Heidi Gardner, Lochlyn Munro",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Description = "26 år efter att ha sprungit ifrån en misstänkt välbekant maskerad mördare (“Ghostface”), är original-fyran måltavla för mördaren igen och ingen skräckfilms-serie går säker. Marlon Wayans (“Shorty”), Shawn Wayans (“Ray”), Anna Faris (“Cindy”) och Regina Hall (“Brenda”) återförenas i Scary Movie, tillsammans med återvändande favoriter och nya ansikten, för att hugga sig igenom reboots, nyinspelningar, reboots på nyinspelningar, prequels, sequels, spin-offs, arthouse-horror, ursprungshistorier, allting som anses vara ikoniskt , och vartenda “sista kapitel” som verkligen inte är det sista.\n\nIngenting är heligt. Inget berättargrepp går säkert. Alla gränser korsas. Bröderna Wayans är tillbaka för att cancellera cancel-kulturen.",
                            Director = "Michael Tiddes",
                            DurationMinutes = 95,
                            Genre = "Skräck, Komedi",
                            ImageUrl = "/images/scarymovie.jpg",
                            IsShowing = false,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Scary Movie",
                            Premiere = new DateOnly(2026, 6, 5),
                            Price = 159.0,
                            Title = "Scary Movie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
