// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApi.Data;

#nullable disable

namespace MoviesApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520183730_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MoviesApi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShowing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Premiere")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actors = "Jack Reynor, Laia Costa, Hayat Kamille",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Director = "Lee Cronin",
                            DurationMinutes = 134,
                            Genre = "Skräck",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Lee Cronin's The Mummy",
                            Premiere = new DateOnly(2026, 4, 17),
                            Price = 169.0,
                            Title = "The Mummy"
                        },
                        new
                        {
                            Id = 2,
                            Actors = "Michael Johnston, Inde Navarrette",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Director = "Curry Barker",
                            DurationMinutes = 108,
                            Genre = "Skräck",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Obsession",
                            Premiere = new DateOnly(2026, 5, 15),
                            Price = 189.0,
                            Title = "Obsession"
                        },
                        new
                        {
                            Id = 3,
                            Actors = "Okänd",
                            AgeRating = "Från 7 år: Får ses på bio av barn under 7 år i vuxens sällskap.",
                            Director = "Okänd",
                            DurationMinutes = 85,
                            Genre = "Familj",
                            IsShowing = true,
                            OriginalLanguage = "Svenska",
                            OriginalTitle = "Fårdetektiverna",
                            Premiere = new DateOnly(2026, 5, 1),
                            Price = 119.0,
                            Title = "Fårdetektiverna"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
