// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesApi.Data;

#nullable disable

namespace MoviesApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520214727_AddDescription")]
    partial class AddDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("MoviesApi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actors")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsShowing")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Premiere")
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Actors = "Jack Reynor, Laia Costa, Hayat Kamille",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Description = "",
                            Director = "Lee Cronin",
                            DurationMinutes = 134,
                            Genre = "Skräck",
                            ImageUrl = "/images/mummy.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Lee Cronin's The Mummy",
                            Premiere = new DateOnly(2026, 4, 17),
                            Price = 169.0,
                            Title = "The Mummy"
                        },
                        new
                        {
                            Id = 4,
                            Actors = "Michael Johnston, Inde Navarrette, Andy Richter, Cooper Tomlinson, Megan Lawless, Haley Fitzgerald, Darin Toonder, Chloe Breen, Anthony Pavone",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Description = "",
                            Director = "Curry Barker",
                            DurationMinutes = 108,
                            Genre = "Skräck",
                            ImageUrl = "/images/obsession.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Obsession",
                            Premiere = new DateOnly(2026, 5, 15),
                            Price = 189.0,
                            Title = "Obsession"
                        },
                        new
                        {
                            Id = 1,
                            Actors = "Hugh Jackman, Emma Thompson, Bella Ramsey",
                            AgeRating = "Från 7 år: Får ses på bio av barn under 7 år i vuxens sällskap.",
                            Description = "",
                            Director = "Kyle Balda",
                            DurationMinutes = 109,
                            Genre = "Familj",
                            ImageUrl = "/images/fardetektiverna.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "The Sheep Detectives",
                            Premiere = new DateOnly(2026, 5, 8),
                            Price = 119.0,
                            Title = "Fårdetektiverna"
                        },
                        new
                        {
                            Id = 3,
                            Actors = "Karl Urban, Hiroyuki Sanada, Martyn Ford, Lewis Tan, Damon Herriman, Tati Gabrielle, Adeline Rudolph, Tadanobu Asano, Josh Lawson, Jessica McNamee, Mehcad Brooks, Ludi Lin, Joe Taslim, Chin Han, Ana Thu Nguyen, Desmond Chiam, Julian Weeks, Max Huang, CJ. Bloomfield",
                            AgeRating = "Från 15 år: Får ses på bio av den som fyllt 11 år i sällskap med vuxen.",
                            Description = "",
                            Director = "Simon McQuoid",
                            DurationMinutes = 115,
                            Genre = "Action",
                            ImageUrl = "/images/mortalkombat.jpg",
                            IsShowing = true,
                            OriginalLanguage = "Engelska",
                            OriginalTitle = "Mortal Kombat II",
                            Premiere = new DateOnly(2026, 5, 8),
                            Price = 159.0,
                            Title = "Mortal Kombat II"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
